"""
partially generated by Google bard (https://bard.google.com/) + with some modification by Abdulla Aldoseri
"""

def divide_and_conquer_max(array):
  """
  Finds the max element of an array using the divide and conquer algorithm.

  Args:
    array: A list of numbers.

  Returns:
    The max element of the array.
  """

  if len(array) == 1:
    return array[0]
  else:
    mid = len(array) // 2
    left = divide_and_conquer_max(array[:mid])
    right = divide_and_conquer_max(array[mid:])
    if(right > left):
      return right
    else:
      return left


def main():
    array = [14,29,11]
    sum = divide_and_conquer_max(array)
    print(sum)

if __name__ == "__main__":
    main()
    
