"""
Generated by Google bard (https://bard.google.com/)
"""

def divide_and_conquer_odd_even_pair(array):

  if len(array) == 1:
    return True
  else:
    mid = len(array) // 2
    left = divide_and_conquer_odd_even_pair(array[:mid])
    right = divide_and_conquer_odd_even_pair(array[mid:])
    
    return left and right and array[mid - 1] % 2 != array[mid] % 2


def main():
    array = [1,2,3,4,5]
    result = divide_and_conquer_odd_even_pair(array)
    print(result)

if __name__ == "__main__":
    main()
