"""
Generated by Google bard (https://bard.google.com/)
"""

def divide_and_conquer_sum(array):
  """
  Finds the sum of an array using the divide and conquer algorithm. (3 divides)

  Args:
    array: A list of numbers.

  Returns:
    The sum of the array.
  """

  if len(array) == 1:
    return array[0]
  elif(len(array)==2):
    return array[0] + array[1]
  else:
    mid_fst = len(array) // 3
    mid_2nd = 2*(len(array)) // 3

    left_sum = divide_and_conquer_sum(array[:mid_fst])
    center_sum = divide_and_conquer_sum(array[mid_fst:mid_2nd])
    right_sum = divide_and_conquer_sum(array[mid_2nd:])
    return left_sum + center_sum+ right_sum


def main():
    array = [5,5,5,6]
    sum = divide_and_conquer_sum(array)
    print(sum)

if __name__ == "__main__":
    main()
