"""
Generated by Google bard (https://bard.google.com/)
"""

def divide_and_conquer_sortable(array):

  if len(array) == 1:
    return True
  else:
    mid = len(array) // 2
    left = divide_and_conquer_sortable(array[:mid])
    right = divide_and_conquer_sortable(array[mid:])
    
    return left and right and array[mid-1] <= array[mid]


def main():
    array = [1,2,4,5,5]
    sum = divide_and_conquer_sortable(array)
    print(sum)

if __name__ == "__main__":
    main()
